# Generated by Django 2.1.7 on 2019-03-18 15:34

import diagnosis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.ForeignKey(on_delete=models.SET(diagnosis.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
