# Generated by Django 2.1.7 on 2019-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20190318_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='question',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='answer',
            field=models.ManyToManyField(to='diagnosis.Answer'),
        ),
    ]
