# Generated by Django 2.1.7 on 2019-03-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_auto_20190319_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
