# Generated by Django 2.1.7 on 2019-03-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_auto_20190319_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Answer'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Question'),
        ),
        migrations.AddField(
            model_name='diagnosisquestionanswer',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.QuestionAnswer'),
        ),
    ]
