# Generated by Django 2.1.7 on 2019-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0008_remove_diagnosis_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisquestionanswer',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='diagnosisquestionanswer',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='answer',
            field=models.ManyToManyField(to='diagnosis.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
        migrations.DeleteModel(
            name='DiagnosisQuestionAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
