# Generated by Django 2.1.7 on 2019-03-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0010_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='answer',
        ),
    ]
