# Generated by Django 2.1.7 on 2019-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0011_remove_diagnosis_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassName',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='answer',
            field=models.ManyToManyField(to='diagnosis.Question'),
        ),
    ]
