# Generated by Django 2.1.7 on 2019-04-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0013_auto_20190327_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
