# Generated by Django 2.1.7 on 2019-04-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0014_auto_20190401_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Answer')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Diagnosis')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('diagnosis', 'question')},
        ),
    ]
