# Generated by Django 2.1.7 on 2019-04-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0017_auto_20190415_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Question'),
            preserve_default=False,
        ),
    ]
