# Generated by Django 2.1.7 on 2019-04-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0018_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquirerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Inquirer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inquirerquestion',
            unique_together={('inquirer', 'question')},
        ),
    ]
