# Generated by Django 2.1.7 on 2019-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0024_auto_20190416_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirer',
            name='ANN_model',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
