# Generated by Django 2.1.7 on 2019-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0027_auto_20190422_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirer',
            old_name='ANN_model',
            new_name='solver',
        ),
        migrations.AddField(
            model_name='inquirer',
            name='is_ann',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
