# Generated by Django 2.1.7 on 2019-04-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0028_auto_20190429_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
