# Generated by Django 2.1.7 on 2019-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0029_auto_20190430_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
