# Generated by Django 2.1.7 on 2019-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0031_inquirer_medical_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(default='images/no-profile.jpg', upload_to='images/'),
        ),
    ]
